on: [push, pull_request]
name: Tests-linux
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.18.0-rc1'
      - name: Tests
        run: go test -v -race ./...
